version: "3"

services:
  web-server:
    build: ./www
    depends_on:
      - api-server
    ports:
      - "80:80"
  api-server:
    build: ./api
  web-crawler:
    build: ./crawler
    depends_on:
      - api-server
    environment:
      - CRAWL_FOR=120
      - START_AT=https://www.python.org/
