version: "3"

services:
  web-server:
    build: ./www
    depends_on:
      - api-server
    ports:
      - "80:80"
  api-server:
    build: ./api
    depends_on:
      - db-server
  web-crawler:
    build: ./crawler
    depends_on:
      - api-server
    environment:
      - CRAWL_FOR=120
      - START_AT=https://www.wikipedia.org/
  db-server:
    build: ./database
    environment:
      - POSTGRES_PASSWORD=admin
